name: learn-github-actions
on: [push]
# https://github.com/actions
jobs:
  run-maven-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
#          https://github.com/actions/setup-java
          distribution: 'adopt' # See 'Supported distributions' for available options
          java-version: '11'
      - name: Build project with Maven
        run: mvn -B package --file pom.xml